print('My name is Ebony Cornett.')
print()
print('I currently work as the Registrar at Bishop Dunne Catholic School in Dallas, Texas. I am also an alumna of Bishop Dunne.')
print()
print('As the Registrar, I am responsible for maintaining student records, managing enrollment processes, and ensuring all students meet the graduation requirements. I enjoy working with students and their families to support their academic journeys.')
print()
print('My hobbies include step aerobics, traveling to new and exciting places, and spending time with my coworkers. I also sitting in nature and reading books.')
print()
print('I am pursuing this degree in Computer Science to better understand programming and coding, so I can migrate to Software Engineering.')
